### ISSUE TITLE
Público fora da plataforma Nónio

### ISSUE THREAD

**Issue by marado** [tomahock/anti-nonio#12]
De acordo com eles próprios:
https://www.publico.pt/2019/12/03/tecnologia/noticia/publico-sai-plataforma-nonio-1896067

O site deve ser actualizado para reflectir esta mudança.

**Comment by tomahock** [comment]
Sem dúvida.

Vou ver se consigo fazer update ASAP!

**Comment by brunomiguel** [comment]
Aparentemente ainda está a usar o Nónio, de acordo com o HTML
```
<div class="login-form__signup">
                        <p class="login-form__cta-text login-form__cta-text--signup">Não tem uma conta? <a href="javascript:void(0);" class="login-form__cta-link login-form__button--oath-nonio" data-screen-set="gigya-register-screen">Registe-se gratuitamente</a></p>
                    </div>
```
Mas ainda não vi se está a ser carregado via JS
